@baseUrl = http://localhost:3333

# @name create_trip
POST {{baseUrl}}/trips
Content-Type: application/json

{ 
  "destination": "Tokyo", 
  starts_at: "2025-07-01", 
  ends_at: "2025-07-20",
  emails_to_invite: ["guilherme@example.com.br"], 
  owner_name: "Guilherme Bezerra", 
  owner_email: "guilherme@example.com.br"
}